-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	[PPMS_PEARL]
-- // MODULO:			REPORTE DE MATERIAL ESCANEADO
-- // OPERACION:		LIBERACION / STORED PROCEDURE
-- //////////////////////////////////////////////////////////////
-- // Autor:			FEG
-- // Fecha creación:	17/FEB/2022
-- //////////////////////////////////////////////////////////////  

USE [DATA_02]
GO


-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_ESTACION_ESCANEO_HEADER_RPT]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_ESTACION_ESCANEO_HEADER_RPT]
GO

/*
 EXEC	[dbo].[PG_ESTACION_ESCANEO_HEADER_RPT] 0,0, 400, '2022-02-01', '2022-02-17', 1
*/

CREATE PROCEDURE [dbo].[PG_ESTACION_ESCANEO_HEADER_RPT]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT, 
	-- ===========================
	@PP_ESTACION				INT,
	@PP_F_INICIAL				DATE,
	@PP_F_FIN					DATE,
	@PP_SECCION_DIA				INT
AS

	-- ///////////MATERIAL EN ESPERA DE SER LIBERADO POR CALIDAD/////////////////////////////////////
	DECLARE @VP_N_CAJAS INT = 0

	IF @PP_ESTACION = 400 -- #400 CERTIFICACION 
		BEGIN
			SELECT	@VP_N_CAJAS = COUNT([K_MATERIAL_PROGRAMADO])
			FROM [MATERIAL_PROGRAMADO] (NOLOCK) 
			WHERE K_TIPO_EVENTO_KIT IN ( 300, 400 ) --#300 INSP. PERF. #400 CERTIFICACION 

			IF @VP_N_CAJAS IS NULL
				SET @VP_N_CAJAS = 0
		END

	-- /////////SE MUESTRA EL RESULTADO//////////////
	SELECT	@PP_F_INICIAL	AS FECHA_INICIO,
			@PP_F_FIN		AS FECHA_FINAL,
			@PP_SECCION_DIA	AS SECCION_DIA,
			@VP_N_CAJAS		AS N_CAJAS
	
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> LISTADO
-- //////////////////////////////////////////////////////////////
-- USE [DATA_02]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_ESTACION_ESCANEO_X_DIA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_ESTACION_ESCANEO_X_DIA]
GO

/*
	EXEC	[dbo].[PG_ESTACION_ESCANEO_X_DIA] 0, 144, 400, '2022-02-16', '2022-02-16' -- CERTIFICACION
	EXEC	[dbo].[PG_ESTACION_ESCANEO_X_DIA] 0, 144, 410, '2022-02-16', '2022-02-16' -- LIBERACION QC
*/

CREATE PROCEDURE [dbo].[PG_ESTACION_ESCANEO_X_DIA]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_ESTACION				INT,
	@PP_F_INICIAL				DATE,
	@PP_F_FIN					DATE
AS

	SELECT	CONVERT( DATE, F_LOG) AS FECHA,
			COUNT([K_MATERIAL_PROGRAMADO_LOG]) AS N_CAJA
	FROM [MATERIAL_PROGRAMADO_LOG] (NOLOCK) 
	WHERE K_TIPO_EVENTO_KIT = @PP_ESTACION 
	AND CONVERT( DATE, F_LOG) >= @PP_F_INICIAL
	AND CONVERT( DATE, F_LOG) <= @PP_F_FIN
	GROUP BY  CONVERT( DATE, F_LOG)
	ORDER BY CONVERT( DATE, F_LOG)
	
	-- //////////////////////////////////////////////////////////////
	-- //////////////////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> LISTADO
-- //////////////////////////////////////////////////////////////
-- USE [DATA_02]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_ESTACION_ESCANEO_X_DIA_MODELO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_ESTACION_ESCANEO_X_DIA_MODELO]
GO

/*
	EXEC	[dbo].[PG_ESTACION_ESCANEO_X_DIA_MODELO] 0, 144, 400, '2022-02-16', '2022-02-16' -- CERTIFICACION
	EXEC	[dbo].[PG_ESTACION_ESCANEO_X_DIA_MODELO] 0, 144, 410, '2022-02-16', '2022-02-16' -- LIBERACION QC
*/

CREATE PROCEDURE [dbo].[PG_ESTACION_ESCANEO_X_DIA_MODELO]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_ESTACION				INT,
	@PP_F_INICIAL				DATE,
	@PP_F_FIN					DATE
AS

	SELECT	CONVERT( DATE, F_LOG) AS FECHA,
			LEFT(LTRIM(RTRIM(CHANGELEVEL)), 3) AS MODELO,
			COUNT([K_MATERIAL_PROGRAMADO_LOG]) AS N_CAJA
	FROM [MATERIAL_PROGRAMADO_LOG] (NOLOCK) 
	INNER JOIN ccjoblin_sql (NOLOCK) ON LTRIM(RTRIM(ccjoblin_sql.jobno)) + RIGHT('000'+ CONVERT(VARCHAR(5),ser_no), 3) = SERIAL
	WHERE K_TIPO_EVENTO_KIT = @PP_ESTACION 
	AND CONVERT( DATE, F_LOG) >= @PP_F_INICIAL
	AND CONVERT( DATE, F_LOG) <= @PP_F_FIN
	GROUP BY  CONVERT( DATE, F_LOG), LEFT(LTRIM(RTRIM(CHANGELEVEL)), 3)
	ORDER BY LEFT(LTRIM(RTRIM(CHANGELEVEL)), 3)
	
	-- //////////////////////////////////////////////////////////////
	-- //////////////////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> LISTADO
-- //////////////////////////////////////////////////////////////
-- USE [DATA_02]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_ESTACION_ESCANEO_X_DIA_MODELO_TURNO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_ESTACION_ESCANEO_X_DIA_MODELO_TURNO]
GO

/*
	EXEC	[dbo].[PG_ESTACION_ESCANEO_X_DIA_MODELO_TURNO] 0, 144, 400, '2022-02-16', '2022-02-16', 3 -- CERTIFICACION
	EXEC	[dbo].[PG_ESTACION_ESCANEO_X_DIA_MODELO_TURNO] 0, 144, 410, '2022-02-16', '2022-02-16', 1 -- LIBERACION QC
*/

CREATE PROCEDURE [dbo].[PG_ESTACION_ESCANEO_X_DIA_MODELO_TURNO]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_ESTACION				INT,
	@PP_F_INICIAL				DATE,
	@PP_F_FIN					DATE,
	@PP_TURNO					INT
AS

	SELECT	CONVERT( DATE, F_LOG) AS FECHA,
			LEFT(LTRIM(RTRIM(CHANGELEVEL)), 3) AS MODELO,
			COUNT([K_MATERIAL_PROGRAMADO_LOG]) AS N_CAJA
	FROM [MATERIAL_PROGRAMADO_LOG] (NOLOCK) 
	INNER JOIN ccjoblin_sql (NOLOCK) ON LTRIM(RTRIM(ccjoblin_sql.jobno)) + RIGHT('000'+ CONVERT(VARCHAR(5),ser_no), 3) = SERIAL
	WHERE K_TIPO_EVENTO_KIT = @PP_ESTACION 
	AND CONVERT( DATE, F_LOG) >= @PP_F_INICIAL
	AND CONVERT( DATE, F_LOG) <= @PP_F_FIN
	AND ( CASE WHEN FORMAT(CAST(F_LOG AS TIME(0)), N'hhmmss') > 0 AND FORMAT(CAST(F_LOG AS TIME(0)), N'hhmmss')  < 60002  THEN 3
				WHEN FORMAT(CAST(F_LOG AS TIME(0)), N'hhmmss') > 60001 AND FORMAT(CAST(F_LOG AS TIME(0)), N'hhmmss')  < 153001 THEN 1
				ELSE 2 END ) = @PP_TURNO 
	GROUP BY  CONVERT( DATE, F_LOG), LEFT(LTRIM(RTRIM(CHANGELEVEL)), 3)
	ORDER BY LEFT(LTRIM(RTRIM(CHANGELEVEL)), 3)
	
	-- //////////////////////////////////////////////////////////////
	-- //////////////////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> LISTADO
-- //////////////////////////////////////////////////////////////
-- USE [DATA_02]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_ESTACION_ESCANEO_X_DIA_X_TURNO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_ESTACION_ESCANEO_X_DIA_X_TURNO]
GO

/*
	EXEC	[dbo].[PG_ESTACION_ESCANEO_X_DIA_X_TURNO] 0, 144, 400, '2022-02-16', '2022-02-16', 3
*/

CREATE PROCEDURE [dbo].[PG_ESTACION_ESCANEO_X_DIA_X_TURNO]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_ESTACION				INT,
	@PP_F_INICIAL				DATE,
	@PP_F_FIN					DATE,
	@PP_TURNO					INT
AS

	SELECT	CONVERT( DATE, F_LOG) AS FECHA,
			COUNT([K_MATERIAL_PROGRAMADO_LOG]) AS N_CAJA
	FROM [MATERIAL_PROGRAMADO_LOG] (NOLOCK) 
	WHERE K_TIPO_EVENTO_KIT = @PP_ESTACION 
	AND CONVERT( DATE, F_LOG) >= @PP_F_INICIAL
	AND CONVERT( DATE, F_LOG) <= @PP_F_FIN
	AND ( CASE WHEN FORMAT(CAST(F_LOG AS TIME(0)), N'hhmmss') > 0 AND FORMAT(CAST(F_LOG AS TIME(0)), N'hhmmss')  < 60002  THEN 3
				WHEN FORMAT(CAST(F_LOG AS TIME(0)), N'hhmmss') > 60001 AND FORMAT(CAST(F_LOG AS TIME(0)), N'hhmmss')  < 153001 THEN 1
				ELSE 2 END ) = @PP_TURNO
	GROUP BY  CONVERT( DATE, F_LOG)
	ORDER BY CONVERT( DATE, F_LOG)
	
	-- //////////////////////////////////////////////////////////////
	-- //////////////////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> LISTADO
-- //////////////////////////////////////////////////////////////
-- USE [DATA_02]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_ESTACION_ESCANEO_X_DIA_X_TURNO_GRAF]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_ESTACION_ESCANEO_X_DIA_X_TURNO_GRAF]
GO

/*
	EXEC	[dbo].[PG_ESTACION_ESCANEO_X_DIA_X_TURNO_GRAF] 0, 144, 400, '2022-02-01', '2022-02-16'
	EXEC	[dbo].[PG_ESTACION_ESCANEO_X_DIA_X_TURNO_GRAF] 0, 144, 410, '2022-02-01', '2022-02-16'
*/

CREATE PROCEDURE [dbo].[PG_ESTACION_ESCANEO_X_DIA_X_TURNO_GRAF]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_ESTACION				INT,
	@PP_F_INICIAL				DATE,
	@PP_F_FIN					DATE
AS

	--///////// SE CREA TABLA TEMPORAL PARA GUARDAR LA INFORMACION //////////////// 
	DECLARE @TBL_MATERIAL_ESCANEADO_DEL_DIA TABLE(
		FECHA		DATE,
		TOTAL_CAJAS	INT
	)
	 
	--///////// SE INGRESA LA INFORMACION DEL 1ER TURNO ////////////////
	INSERT INTO @TBL_MATERIAL_ESCANEADO_DEL_DIA
	SELECT	CONVERT( DATE, F_LOG) AS FECHA,
			COUNT([K_MATERIAL_PROGRAMADO_LOG]) AS N_CAJA
	FROM [MATERIAL_PROGRAMADO_LOG] (NOLOCK) 
	WHERE K_TIPO_EVENTO_KIT = @PP_ESTACION 
	AND CONVERT( DATE, F_LOG) >= @PP_F_INICIAL
	AND CONVERT( DATE, F_LOG) <= @PP_F_FIN
	GROUP BY  CONVERT( DATE, F_LOG)

	--///////// SE CREA TABLA TEMPORAL PARA GUARDAR LA INFORMACION ////////////////
	DECLARE @TBL_MATERIAL_ESCANEADO_DEL_DIA_X_TURNO_1 TABLE(
		FECHA		DATE,
		TOTAL_CAJAS	INT
	)
	 
	--///////// SE INGRESA LA INFORMACION DEL 1ER TURNO ////////////////
	INSERT INTO @TBL_MATERIAL_ESCANEADO_DEL_DIA_X_TURNO_1
	SELECT	CONVERT( DATE, F_LOG) AS FECHA,
			COUNT([K_MATERIAL_PROGRAMADO_LOG]) AS N_CAJA
	FROM [MATERIAL_PROGRAMADO_LOG] (NOLOCK) 
	WHERE K_TIPO_EVENTO_KIT = @PP_ESTACION 
	AND CONVERT( DATE, F_LOG) >= @PP_F_INICIAL
	AND CONVERT( DATE, F_LOG) <= @PP_F_FIN
	AND ( CASE WHEN FORMAT(CAST(F_LOG AS TIME(0)), N'hhmmss') > 0 AND FORMAT(CAST(F_LOG AS TIME(0)), N'hhmmss')  < 60002  THEN 3
				WHEN FORMAT(CAST(F_LOG AS TIME(0)), N'hhmmss') > 60001 AND FORMAT(CAST(F_LOG AS TIME(0)), N'hhmmss')  < 153001 THEN 1
				ELSE 2 END ) = 1
	GROUP BY  CONVERT( DATE, F_LOG)

	--///////// SE CREA TABLA TEMPORAL PARA GUARDAR LA INFORMACION ////////////////
	DECLARE @TBL_MATERIAL_ESCANEADO_DEL_DIA_X_TURNO_2 TABLE(
		FECHA		DATE,
		TOTAL_CAJAS	INT
	)
	 
	--///////// SE INGRESA LA INFORMACION DEL 2DO TURNO ////////////////
	INSERT INTO @TBL_MATERIAL_ESCANEADO_DEL_DIA_X_TURNO_2
	SELECT	CONVERT( DATE, F_LOG) AS FECHA,
			COUNT([K_MATERIAL_PROGRAMADO_LOG]) AS N_CAJA
	FROM [MATERIAL_PROGRAMADO_LOG] (NOLOCK) 
	WHERE K_TIPO_EVENTO_KIT = @PP_ESTACION 
	AND CONVERT( DATE, F_LOG) >= @PP_F_INICIAL
	AND CONVERT( DATE, F_LOG) <= @PP_F_FIN
	AND ( CASE WHEN FORMAT(CAST(F_LOG AS TIME(0)), N'hhmmss') > 0 AND FORMAT(CAST(F_LOG AS TIME(0)), N'hhmmss')  < 60002  THEN 3
				WHEN FORMAT(CAST(F_LOG AS TIME(0)), N'hhmmss') > 60001 AND FORMAT(CAST(F_LOG AS TIME(0)), N'hhmmss')  < 153001 THEN 1
				ELSE 2 END ) = 2
	GROUP BY  CONVERT( DATE, F_LOG)

	--///////// SE CREA TABLA TEMPORAL PARA GUARDAR LA INFORMACION ////////////////
	DECLARE @TBL_MATERIAL_ESCANEADO_DEL_DIA_X_TURNO_3 TABLE(
		FECHA		DATE,
		TOTAL_CAJAS	INT
	)
	 
	--///////// SE INGRESA LA INFORMACION DEL 3ER TURNO ////////////////
	INSERT INTO @TBL_MATERIAL_ESCANEADO_DEL_DIA_X_TURNO_3
	SELECT	CONVERT( DATE, F_LOG) AS FECHA,
			COUNT([K_MATERIAL_PROGRAMADO_LOG]) AS N_CAJA
	FROM [MATERIAL_PROGRAMADO_LOG] (NOLOCK) 
	WHERE K_TIPO_EVENTO_KIT = @PP_ESTACION 
	AND CONVERT( DATE, F_LOG) >= @PP_F_INICIAL
	AND CONVERT( DATE, F_LOG) <= @PP_F_FIN
	AND ( CASE WHEN FORMAT(CAST(F_LOG AS TIME(0)), N'hhmmss') > 0 AND FORMAT(CAST(F_LOG AS TIME(0)), N'hhmmss')  < 60002  THEN 3
				WHEN FORMAT(CAST(F_LOG AS TIME(0)), N'hhmmss') > 60001 AND FORMAT(CAST(F_LOG AS TIME(0)), N'hhmmss')  < 153001 THEN 1
				ELSE 2 END ) = 3
	GROUP BY  CONVERT( DATE, F_LOG)

	-- //////////SE MUESTRAN LOS TOTALES////////////////////////////////////////////////////
	SELECT	DIA.FECHA AS 'Fecha',
			ISNULL(TURNO_1.TOTAL_CAJAS, 0) AS '1er Turno',
			ISNULL(TURNO_2.TOTAL_CAJAS, 0) AS '2do Turno',
			ISNULL(TURNO_3.TOTAL_CAJAS, 0) AS '3er Turno',
			DIA.TOTAL_CAJAS AS 'Total'
	FROM @TBL_MATERIAL_ESCANEADO_DEL_DIA AS DIA
	LEFT JOIN @TBL_MATERIAL_ESCANEADO_DEL_DIA_X_TURNO_1 TURNO_1 ON DIA.FECHA = TURNO_1.FECHA
	LEFT JOIN @TBL_MATERIAL_ESCANEADO_DEL_DIA_X_TURNO_2 TURNO_2 ON DIA.FECHA = TURNO_2.FECHA
	LEFT JOIN @TBL_MATERIAL_ESCANEADO_DEL_DIA_X_TURNO_3 TURNO_3 ON DIA.FECHA = TURNO_3.FECHA
	ORDER BY DIA.FECHA 
	-- //////////////////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> LISTADO
-- //////////////////////////////////////////////////////////////
-- USE [DATA_02]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_ESTACION_ESCANEO_CERTIFICACION_VS_LIBERACION_GRAF]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_ESTACION_ESCANEO_CERTIFICACION_VS_LIBERACION_GRAF]
GO

/*
	EXEC	[dbo].[PG_ESTACION_ESCANEO_CERTIFICACION_VS_LIBERACION_GRAF] 0, 144, '2022-02-01', '2022-02-16'
*/

CREATE PROCEDURE [dbo].[PG_ESTACION_ESCANEO_CERTIFICACION_VS_LIBERACION_GRAF]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_F_INICIAL				DATE,
	@PP_F_FIN					DATE
AS

	--///////// SE CREA TABLA TEMPORAL PARA GUARDAR LA INFORMACION //////////////// 
	DECLARE @TBL_MATERIAL_ESCANEADO_CERTIFICACION TABLE(
		FECHA		DATE,
		TOTAL_CAJAS	INT
	)
	 
	--///////// SE INGRESA LA INFORMACION DEL 1ER TURNO ////////////////
	INSERT INTO @TBL_MATERIAL_ESCANEADO_CERTIFICACION
	SELECT	CONVERT( DATE, F_LOG) AS FECHA,
			COUNT([K_MATERIAL_PROGRAMADO_LOG])
	FROM [MATERIAL_PROGRAMADO_LOG] (NOLOCK) 
	WHERE K_TIPO_EVENTO_KIT = 400 -- CERTIFICACION 
	AND CONVERT( DATE, F_LOG) >= @PP_F_INICIAL
	AND CONVERT( DATE, F_LOG) <= @PP_F_FIN
	GROUP BY  CONVERT( DATE, F_LOG)

	--///////// SE CREA TABLA TEMPORAL PARA GUARDAR LA INFORMACION //////////////// 
	DECLARE @TBL_MATERIAL_ESCANEADO_LIBERACION TABLE(
		FECHA		DATE,
		TOTAL_CAJAS	INT
	)
	 
	--///////// SE INGRESA LA INFORMACION DEL 1ER TURNO ////////////////
	INSERT INTO @TBL_MATERIAL_ESCANEADO_LIBERACION
	SELECT	CONVERT( DATE, F_LOG) AS FECHA,
			COUNT([K_MATERIAL_PROGRAMADO_LOG])
	FROM [MATERIAL_PROGRAMADO_LOG] (NOLOCK) 
	WHERE K_TIPO_EVENTO_KIT = 410 -- LIBERACION_QC 
	AND CONVERT( DATE, F_LOG) >= @PP_F_INICIAL
	AND CONVERT( DATE, F_LOG) <= @PP_F_FIN
	GROUP BY  CONVERT( DATE, F_LOG)


	-- //////////SE MUESTRAN LOS TOTALES////////////////////////////////////////////////////
	SELECT	CERTI.FECHA AS 'Fecha',
			ISNULL(CERTI.TOTAL_CAJAS, 0) AS 'Total Entrada',
			ISNULL(LIB.TOTAL_CAJAS, 0) AS 'Total Salida'
	FROM @TBL_MATERIAL_ESCANEADO_CERTIFICACION AS CERTI
	LEFT JOIN @TBL_MATERIAL_ESCANEADO_LIBERACION LIB ON CERTI.FECHA = LIB.FECHA
	ORDER BY CERTI.FECHA 
	-- //////////////////////////////////////////////////////////////
GO

-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////