
USE DATA_02Pruebas

	SELECT * FROM HOWE.dbo.VISTA_GAFETES WHERE EN_CLASE_EMP < 4
	ORDER BY DP_DEPTO

	SELECT * FROM [DATA_02].[DBO].ccitmidx_sql WHERE LEN(user_def_fld_4) = 3

	SELECT TOP 1	
				KIT_RUTA.K_KIT_RUTA_EVENTO,
				D_KIT_RUTA_EVENTO,
				KIT_RUTA.O_KIT_RUTA_EVENTO
	FROM KIT_RUTA (NOLOCK)
	INNER JOIN KIT_RUTA_EVENTO (NOLOCK) ON KIT_RUTA_EVENTO.K_KIT_RUTA_EVENTO = KIT_RUTA.K_KIT_RUTA_EVENTO
	WHERE ITEM_NO = 'PTLFSCLWLNPA5'
	AND MODELNO = 'WTL'
	AND VERSIONNO = '0013'
	AND KIT_RUTA.O_KIT_RUTA_EVENTO <  4
	ORDER BY KIT_RUTA.O_KIT_RUTA_EVENTO DESC

	SELECT * FROM CCJOBLIN_SQL WHERE JOBNO = '36713'

	SELECT * FROM INVENTARIO_EMBARQUE WHERE SERIAL_1 = '31510010'

	SELECT * FROM KIT_RUTA (NOLOCK) 
	WHERE ITEM_NO =  'PMJYFBLCNPDX9' ORDER BY VERSIONNO DESC
	
	SELECT * FROM KIT_RUTA_EVENTO (NOLOCK)
	
	SELECT TOP 1 D_KIT_RUTA_EVENTO
	FROM [MATERIAL_PROGRAMADO_LOG] (NOLOCK)
	INNER JOIN KIT_RUTA_EVENTO (NOLOCK) ON KIT_RUTA_EVENTO.K_KIT_RUTA_EVENTO = [MATERIAL_PROGRAMADO_LOG].K_TIPO_EVENTO_KIT
	WHERE SERIAL = '33904005 '
	ORDER BY K_MATERIAL_PROGRAMADO_LOG DESC

	SELECT * FROM PPMS_PEARL.DBO.Perforacion where noserie = '34833009'

	SELECT *  FROM [MATERIAL_PROGRAMADO_LOG] (NOLOCK) WHERE K_TIPO_EVENTO_KIT = 220
	--SERIAL like  '35696%'
	--AND  ITEM_NO  IN ('PWLDROBWLCPX7', 'PWLDFCLWLCPX7')
	ORDER BY K_MATERIAL_PROGRAMADO_LOG DESC
	
	SELECT COUNT([K_MATERIAL_PROGRAMADO_LOG]) 
	FROM [MATERIAL_PROGRAMADO_LOG] (NOLOCK)
	WHERE SERIAL = LTRIM(RTRIM('34929')) + RIGHT('000'+ LTRIM(RTRIM(012)),3)   
	AND K_TIPO_EVENTO_KIT >= 400

	SELECT COUNT([K_MATERIAL_PROGRAMADO_LOG]) 
	FROM [MATERIAL_PROGRAMADO_LOG] (NOLOCK)
	WHERE SERIAL = LTRIM(RTRIM('349291')) + RIGHT('000'+ LTRIM(RTRIM(012)),3)   
	AND K_TIPO_EVENTO_KIT >= 300

	SELECT * FROM [MATERIAL_PROGRAMADO_LOG] (NOLOCK) WHERE K_TIPO_EVENTO_KIT = 1
	AND	SERIAL like  '35696013'
	ORDER BY [K_MATERIAL_PROGRAMADO_LOG] asc

	SELECT * FROM COLORES_CONTROLADOS

	SELECT D_USUARIO_PEARL, * FROM [MATERIAL_PROGRAMADO_LOG]
	LEFT JOIN BD_GENERAL.DBO.USUARIO_PEARL ON K_USUARIO_PEARL = K_RESPONSABLE
	WHERE SERIAL LIKE '35696%' AND ESTACION = 'EMBARQUES'

	SELECT * FROM BD_GENERAL.DBO.USUARIO_PEARL

	SELECT * FROM [MATERIAL_PROGRAMADO_LOG]
	WHERE SERIAL in ( '35696013')
	ORDER BY [K_MATERIAL_PROGRAMADO_LOG] DESC
	-- ////////////////////////////////////////////////

	SELECT * FROM ccjoblin_sql WHERE JOBNO IN ('36859') AND SER_NO = 9
	
	SELECT * FROM ccjobhdr_sql WHERE JOBNO IN ('36568') ORDER BY JOBNO
	
	SELECT * FROM PEARL_LOG WHERE JOBNO = '36568'

	SELECT	JOBNO, 
			-- ===========================
			LTRIM(RTRIM(ccjoblin_sql.kit))			AS KIT, 
			LTRIM(RTRIM(ccjoblin_sql.kitdesc))		AS KIT_DESC, 
			CONVERT(INT,ccjoblin_sql.originalqty)	AS ORIGINAL_QTY, 
			LTRIM(RTRIM(ccjoblin_sql.customer))		AS CUSTOMER, 
			ccjoblin_sql.item_no					AS ITEM_NO,
			ccjoblin_sql.Ser_No						AS SER_NO,
			ccjoblin_sql.ChangeLevel				AS CHANGELEVEL,
			-- ===========================
			LTRIM(RTRIM(cccusitm_sql.cus_item_no))	AS CUS_ITEM_NO,
			LTRIM(RTRIM(cccusitm_sql.modelno))		AS MODELNO,
			LTRIM(RTRIM(cccusitm_sql.versionno))	AS VERSIONNO
			-- ===========================
	FROM ccjoblin_sql  (NOLOCK)
	-- ===========================
	INNER JOIN	cccusitm_sql (NOLOCK) ON ccjoblin_sql.Item_No = cccusitm_sql.item_no 
	AND		ccjoblin_sql.customer = cccusitm_sql.cus_no
	AND		cccusitm_sql.versionno = (	SELECT	MAX(CONVERT(INT, versionno)) 
													FROM	cccusitm_sql (NOLOCK)
													WHERE	cccusitm_sql.Item_No = ccjoblin_sql.item_no  
													AND		cccusitm_sql.cus_no = ccjoblin_sql.customer)
	-- ===========================
	WHERE	ccjoblin_sql.jobno = 31503
	-- ===========================
    ORDER BY ccjoblin_sql.jobno, SER_NO
