
USE DATA_02Pruebas

SELECT * FROM HOWE.dbo.VISTA_GAFETES WHERE EN_NUM_EMP = 14848

SELECT * FROM PF_SC

SELECT * FROM [DATA_02].[DBO].ccitmidx_sql WHERE LEN(user_def_fld_4) = 3

SELECT * FROM [DATA_02].[DBO].ccprdstr_sql WHERE ITEM_NO = 'PMWCFBRWLNPT5'    AND modelno = 'WC1' AND versionno=8

SELECT * FROM [DATA_02].[DBO].ccprdstr_sql WHERE ITEM_NO = 'PMWGARMCNPDX9'    AND modelno = 'WKG' AND versionno=24

SELECT top 100 D_KIT_RUTA_EVENTO, KIT_RUTA.* 
FROM KIT_RUTA (NOLOCK)
INNER JOIN KIT_RUTA_EVENTO (NOLOCK) ON KIT_RUTA_EVENTO.K_KIT_RUTA_EVENTO = KIT_RUTA.K_KIT_RUTA_EVENTO
--WHERE ITEM_NO  IN ('PWLDROBWLCPX7', 'PWLDFCLWLCPX7')
WHERE ITEM_NO  IN ('PWLDFCLWLCPX7')
AND MODELNO = 'WDL' AND VERSIONNO = '0014'
and KIT_RUTA.K_KIT_RUTA_EVENTO > 20

SELECT * FROM INVENTARIO_EMBARQUE WHERE SERIAL_1 = '31510010'

SELECT * FROM KIT_RUTA (NOLOCK) WHERE ITEM_NO =  'PMWGARMCNPDX9' ORDER BY VERSIONNO DESC

SELECT * FROM KIT_RUTA_EVENTO (NOLOCK)

 SELECT TOP 1 D_KIT_RUTA_EVENTO
FROM [MATERIAL_PROGRAMADO_LOG] (NOLOCK)
INNER JOIN KIT_RUTA_EVENTO (NOLOCK) ON KIT_RUTA_EVENTO.K_KIT_RUTA_EVENTO = [MATERIAL_PROGRAMADO_LOG].K_TIPO_EVENTO_KIT
WHERE SERIAL = '33904005 '
ORDER BY K_MATERIAL_PROGRAMADO_LOG DESC

SELECT * FROM [MATERIAL_PROGRAMADO_LOG] (NOLOCK) WHERE K_TIPO_EVENTO_KIT = 420
SERIAL = '34463002'
--AND  ITEM_NO  IN ('PWLDROBWLCPX7', 'PWLDFCLWLCPX7')
ORDER BY K_MATERIAL_PROGRAMADO_LOG DESC
SELECT 30 * 0
SELECT * FROM [MATERIAL_PROGRAMADO] (NOLOCK) WHERE SERIAL  = '34463002'
ORDER BY [K_MATERIAL_PROGRAMADO] DESC

SELECT * FROM COLORES_CONTROLADOS

SELECT D_USUARIO_PEARL, * FROM [MATERIAL_PROGRAMADO_LOG]
LEFT JOIN BD_GENERAL.DBO.USUARIO_PEARL ON K_USUARIO_PEARL = K_RESPONSABLE
WHERE SERIAL LIKE '32629%'

SELECT * FROM BD_GENERAL.DBO.USUARIO_PEARL

SELECT * FROM [MATERIAL_PROGRAMADO_LOG]
WHERE SERIAL LIKE '32643%'

	SELECT	SERIAL,  
			[MATERIAL_PROGRAMADO].ITEM_NO,
			originalqty AS CANTIDAD,
			CODIGO_ETIQUETA,
			( CASE WHEN EP_NOMBRE IS NULL THEN 'N/E'
				ELSE CONCAT(EP_NOMBRE, ' ', EP_APELLIDO_PATERNO) END ) AS RESPONSABLE,
			CONVERT(VARCHAR,F_EVENTO, 20) AS F_EVENTO
	FROM [MATERIAL_PROGRAMADO] (NOLOCK)
	INNER JOIN ccjoblin_sql (NOLOCK) ON LTRIM(RTRIM(ccjoblin_sql.jobno)) + RIGHT('000'+ LTRIM(RTRIM(ser_no)),3) = SERIAL
	LEFT JOIN HOWE.dbo.VISTA_GAFETES (NOLOCK) ON VISTA_GAFETES.EN_NUM_EMP = K_RESPONSABLE
	WHERE USUARIO_EVENTO =  'laminacion'
	--AND ESTACION = 'IT-010'
	AND CONVERT(DATE, F_EVENTO) = CONVERT(DATE, GETDATE())
	ORDER BY K_MATERIAL_PROGRAMADO DESC
	-- ////////////////////////////////////////////////

SELECT * FROM ccjoblin_sql WHERE JOBNO IN ('32833') ORDER BY JOBNO 

SELECT * FROM ccjobhdr_sql WHERE JOBNO IN ('32833') ORDER BY JOBNO

SELECT * FROM PEARL_LOG WHERE JOBNO = '32833'
--ITEM_NO IN (SELECT COMP_ITEM_NO FROM [DATA_02].[DBO].ccprdstr_sql WHERE ITEM_NO = 'PMWCFBRWLNPT5'    AND modelno = 'WC1' AND versionno=8)  AND modelno = 'WC1' AND versionno=8

--    ES EL ORDEN CORRECTO DE LOS SPECIAL PROCESS
--    PERFO03 + SHAVE01 + EMBOS06 + LAMIN02 + RECUT04 + QULTN05 + SHAVE07 + LAMIN08 + LAMIN09 + PERFO10 + LAMIN11 + LAMIN12 + LAMIN13 + QULTN14 + ENESPERAUSO

	SELECT	JOBNO, 
			-- ===========================
			LTRIM(RTRIM(ccjoblin_sql.kit))			AS KIT, 
			LTRIM(RTRIM(ccjoblin_sql.kitdesc))		AS KIT_DESC, 
			CONVERT(INT,ccjoblin_sql.originalqty)	AS ORIGINAL_QTY, 
			LTRIM(RTRIM(ccjoblin_sql.customer))		AS CUSTOMER, 
			ccjoblin_sql.item_no					AS ITEM_NO,
			ccjoblin_sql.Ser_No						AS SER_NO,
			ccjoblin_sql.ChangeLevel				AS CHANGELEVEL,
			-- ===========================
			LTRIM(RTRIM(cccusitm_sql.cus_item_no))	AS CUS_ITEM_NO,
			LTRIM(RTRIM(cccusitm_sql.modelno))		AS MODELNO,
			LTRIM(RTRIM(cccusitm_sql.versionno))	AS VERSIONNO
			-- ===========================
	FROM ccjoblin_sql  (NOLOCK)
	-- ===========================
	INNER JOIN	cccusitm_sql (NOLOCK) ON ccjoblin_sql.Item_No = cccusitm_sql.item_no 
	AND		ccjoblin_sql.customer = cccusitm_sql.cus_no
	AND		cccusitm_sql.versionno = (	SELECT	MAX(CONVERT(INT, versionno)) 
													FROM	cccusitm_sql (NOLOCK)
													WHERE	cccusitm_sql.Item_No = ccjoblin_sql.item_no  
													AND		cccusitm_sql.cus_no = ccjoblin_sql.customer)
	-- ===========================
	WHERE	ccjoblin_sql.jobno = 31503
	-- ===========================
    ORDER BY ccjoblin_sql.jobno, SER_NO